Adds test for presence of report file

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -18,8 +18,7 @@ workflows:
         inputs:
         - content: |
             #!/bin/bash
-            echo "Just an example 'secrets' print."
-            echo "The value of 'A_SECRET_PARAM' is: $A_SECRET_PARAM"
+            cp ./sample_podfile.lock ./_tmp/Podfile.lock
     - change-workdir:
         title: Switch working dir to test / _tmp dir
         description: |-
@@ -33,20 +32,18 @@ workflows:
         - is_create_path: true
     - path::./:
         title: Step Test
-        description: |-
-          The example input has a default value,
-          you can overwrite it if you want to, just like we did below,
-          but the step would use the default value specified in the `step.yml`
-          file if you would not specify another value.
         run_if: true
         inputs:
-        - example_step_input: Example Step Input's value
+        - app_title: "Test App"
     - script:
         inputs:
         - content: |
             #!/bin/bash
-            echo "This output was generated by the Step (EXAMPLE_STEP_OUTPUT): $EXAMPLE_STEP_OUTPUT"
-
+            echo "Checking for presence of analysis report ..."
+            if [ ! -f "${BITRISE_DEPLOY_DIR}/dependency-check-report.html" ]; then
+                echo "Could not find generated analysis report!"
+                exit 1
+            fi
 
   # ----------------------------------------------------------------
   # --- workflows to Share this step into a Step Library
